safe: true
pygments: true
baseurl: /
permalink: pretty

authors:
  struan:
    display_name: Struan
  matthew:
    display_name: Matthew

logo_url: "https://twimg0-a.akamaihd.net/profile_images/1901025535/fms-twitter-avatar_reasonably_small.jpg"